[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build", "cp -r public .next/standalone/public", "cp -r .next/static .next/standalone/.next/static"]

[start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_OPTIONS = "--max-old-space-size=6144"
NEXT_DISABLE_ESLINT = "1"
NEXT_DISABLE_TYPE_CHECK = "1"
