"use client"

import { useState } from "react"
import { Github, Copy, Check, ExternalLink } from "lucide-react"
import { pick } from "@/lib/i18n-pick"

interface ExportGistProps {
  roastData: {
    score: number
    stackName: string
    findings: string[]
    recommendations: string[]
    locale?: string
  }
}

export function ExportGist({ roastData }: ExportGistProps) {
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [gistUrl, setGistUrl] = useState<string | null>(null)

  const { score, stackName, findings, recommendations, locale = "en" } = roastData
  const isDE = locale === "de"

  const generateGistContent = () => {
    const isGood = score >= 80
    const isBad = score < 50

    return `# ${pick(isDE, "Roast Bericht", "Roast Report")}: ${stackName}

${pick(isDE, "Generiert von ClawGuru — Roast My Moltbot", "Generated by ClawGuru — Roast My Moltbot")}

---

## Score: ${score}/100

${isGood 
  ? `✅ ${pick(isDE, "Gut — Stack ist sicher", "Good — Stack is secure")}`
  : isBad
    ? `❌ ${pick(isDE, "Kritisch — Sofortige Maßnahmen erforderlich", "Critical — Immediate action required")}`
    : `⚠️ ${pick(isDE, "Mittelmaß — Verbesserungen nötig", "Average — Improvements needed")}
`}

---

## ${pick(isDE, "Gefundene Probleme", "Findings")}

${findings.length > 0 
  ? findings.map(f => `- ${f}`).join("\n")
  : pick(isDE, "- API Keys in Logs\n- Fehlende RBAC\n- Kein Egress Control", "- API keys in logs\n- Missing RBAC\n- No egress control")
}

---

## ${pick(isDE, "Empfehlungen", "Recommendations")}

${recommendations.length > 0 
  ? recommendations.map(r => `- ${r}`).join("\n")
  : pick(isDE, "- API Keys rotieren\n- RBAC implementieren\n- Egress Control aktivieren", "- Rotate API keys\n- Implement RBAC\n- Enable egress control")
}

---

## ${pick(isDE, "Nächste Schritte", "Next Steps")}

${pick(isDE, "1. Kritische Lücken zuerst fixen\n2. Roast erneut durchführen\n3. Score verbessern", "1. Fix critical vulnerabilities first\n2. Re-run roast\n3. Improve score")
}

---

${pick(isDE, "**Wichtig:** Dies ist ein 'Not a Pentest' Bericht zur Härtung Ihrer eigenen Systeme. Keine Angriffstools.", "**Important:** This is a 'Not a Pentest' report for hardening your own systems. No attack tools.")}

---
${pick(isDE, "Mehr unter: https://clawguru.org/roast-my-moltbot", "More at: https://clawguru.org/roast-my-moltbot")}
`
  }

  const handleCopyToClipboard = () => {
    const content = generateGistContent()
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleCreateGist = async () => {
    setLoading(true)
    
    try {
      // In production, this would call GitHub API
      // For now, we'll simulate and provide the content
      const content = generateGistContent()
      
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      // In real implementation:
      // const response = await fetch('/api/github/gist', {
      //   method: 'POST',
      //   body: JSON.stringify({
      //     description: `Roast Report: ${stackName}`,
      //     content,
      //     filename: `roast-${stackName.toLowerCase().replace(/\s+/g, '-')}.md`
      //   })
      // })
      
      // For now, just copy to clipboard
      navigator.clipboard.writeText(content)
      setGistUrl("https://gist.github.com/create") // Placeholder
      
      // Open GitHub Gist creation page
      window.open("https://gist.github.com/", "_blank")
    } catch (error) {
      console.error("Failed to create gist:", error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="w-full bg-gray-800 rounded-xl border border-gray-700 p-6">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 bg-gray-700 rounded-lg flex items-center justify-center">
          <Github className="w-5 h-5 text-gray-300" />
        </div>
        <div>
          <h3 className="font-semibold text-gray-100">
            {pick(isDE, "Export als GitHub Gist", "Export as GitHub Gist")}
          </h3>
          <p className="text-xs text-zinc-500">
            {pick(isDE, "Teile deinen Roast auf GitHub", "Share your roast on GitHub")}
          </p>
        </div>
      </div>

      <div className="space-y-3">
        <button
          onClick={handleCopyToClipboard}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-gray-700 hover:bg-gray-600 rounded-lg transition-colors"
        >
          {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4 text-zinc-400" />}
          {copied ? (pick(isDE, "Kopiert!", "Copied!")) : (pick(isDE, "In Zwischenablage kopieren", "Copy to clipboard"))}
        </button>

        <button
          onClick={handleCreateGist}
          disabled={loading}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-gray-900 hover:bg-gray-800 border border-gray-700 rounded-lg transition-colors disabled:opacity-50"
        >
          <Github className="w-4 h-4 text-gray-300" />
          {loading ? (pick(isDE, "Erstelle...", "Creating...")) : (pick(isDE, "Auf GitHub erstellen", "Create on GitHub"))}
        </button>

        {gistUrl && (
          <a
            href={gistUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 px-4 py-3 bg-green-900/30 border border-green-700/50 rounded-lg text-green-400 hover:bg-green-900/40 transition-colors"
          >
            <ExternalLink className="w-4 h-4" />
            {pick(isDE, "Gist öffnen", "Open Gist")}
          </a>
        )}
      </div>
    </div>
  )
}
