// WORLD BEAST UPGRADE: lib/bounties.ts
// Bounty catalog data – shared between the page and API routes.

export const BOUNTIES = [
  {
    id: "bounty-001",
    title: "Undokumentierter Docker Daemon Exploit",
    description: "Finde und dokumentiere einen neuen Angriffspfad auf den Docker Daemon via Unix Socket Privilege Escalation.",
    rewardEur: 500,
    difficulty: "hard" as const,
    category: "container-security",
    tags: ["docker", "privilege-escalation", "linux"],
    status: "open" as const,
    submissions: 3,
    expiresAt: "2026-06-30",
  },
  {
    id: "bounty-002",
    title: "Kubernetes RBAC Misconfiguration Pattern",
    description: "Identifiziere eine neue häufige RBAC-Fehlkonfiguration in Managed K8s (EKS/GKE/AKS) und erstelle ein Runbook.",
    rewardEur: 300,
    difficulty: "medium" as const,
    category: "kubernetes",
    tags: ["kubernetes", "rbac", "cloud"],
    status: "open" as const,
    submissions: 7,
    expiresAt: "2026-05-31",
  },
  {
    id: "bounty-003",
    title: "Nginx Config Bypass Technique",
    description: "Dokumentiere eine neue Nginx-Konfigurationsschwachstelle die Reverse-Proxy-Auth-Bypass ermöglicht.",
    rewardEur: 250,
    difficulty: "medium" as const,
    category: "webserver",
    tags: ["nginx", "auth-bypass", "proxy"],
    status: "open" as const,
    submissions: 12,
    expiresAt: "2026-04-30",
  },
  {
    id: "bounty-004",
    title: "GitHub Actions Secret Exfiltration",
    description: "Finde eine neue Technik zur Secret-Exfiltration in GitHub Actions Workflows (fork PRs, etc.).",
    rewardEur: 400,
    difficulty: "hard" as const,
    category: "cicd",
    tags: ["github-actions", "secrets", "cicd"],
    status: "open" as const,
    submissions: 2,
    expiresAt: "2026-07-31",
  },
  {
    id: "bounty-005",
    title: "Terraform State File Exposure",
    description: "Dokumentiere Angriffspfade auf exponierte Terraform State Files in Cloud Storage.",
    rewardEur: 150,
    difficulty: "easy" as const,
    category: "iac",
    tags: ["terraform", "secrets", "s3"],
    status: "open" as const,
    submissions: 18,
    expiresAt: "2026-04-15",
  },
  {
    id: "bounty-006",
    title: "Redis AUTH Bypass via RESP3",
    description: "Untersuche potentielle Auth-Bypass-Vektoren in Redis 7.x via RESP3 Protokoll.",
    rewardEur: 600,
    difficulty: "hard" as const,
    category: "database",
    tags: ["redis", "auth-bypass", "protocol"],
    status: "in-review" as const,
    submissions: 1,
    expiresAt: "2026-08-31",
  },
]

export type Bounty = (typeof BOUNTIES)[number]
