'use client'
// WORLD BEAST UPGRADE: app/fix/[slug]/FixPageClient.tsx
// Client component: code display, copy-to-clipboard, and GitHub PR preparation.

import { useState } from "react"
import type { FixCodeResult } from "@/lib/agents/fix-agent"

interface Props {
  slug: string
  fixData: FixCodeResult | null
}

// WORLD BEAST UPGRADE: Code block with copy button
function CodeBlock({ label, code, lang }: { label: string; code: string; lang: string }) {
  const [copied, setCopied] = useState(false)

  function copy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div className="rounded-xl overflow-hidden glass-card mb-4">
      <div className="flex items-center justify-between px-4 py-2 border-b border-white/5">
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-gray-500">{lang}</span>
          <span className="text-xs font-bold text-gray-300">{label}</span>
        </div>
        <button
          onClick={copy}
          className="text-xs px-3 py-1 rounded-lg transition-all duration-200 font-mono"
          style={{
            background: copied ? "rgba(0, 255, 157, 0.15)" : "rgba(255,255,255,0.06)",
            color: copied ? "#00ff9d" : "#aaa",
            border: `1px solid ${copied ? "rgba(0, 255, 157, 0.3)" : "rgba(255,255,255,0.08)"}`,
          }}
        >
          {copied ? "✅ Copied" : "📋 Copy"}
        </button>
      </div>
      <pre className="p-4 text-sm text-gray-300 overflow-x-auto font-mono leading-relaxed">
        <code>{code}</code>
      </pre>
    </div>
  )
}

export default function FixPageClient({ slug, fixData }: Props) {
  const [prMode, setPrMode] = useState(false)
  const [prCopied, setPrCopied] = useState(false)

  if (!fixData) {
    return (
      <div className="p-8 rounded-2xl glass-panel text-center">
        <div className="text-4xl mb-4">⚠️</div>
        <div className="font-black text-xl mb-2">Fix code not available</div>
        <p className="text-gray-400 text-sm mb-6">
          Gemini API key is not configured or the fix could not be generated for this runbook.
        </p>
        <div className="flex justify-center gap-3 flex-wrap">
          <a
            href={`/runbook/${slug}`}
            className="px-6 py-3 rounded-2xl font-black text-black transition-all duration-300"
            style={{ background: "linear-gradient(135deg, #00ff9d, #00b8ff)" }}
          >
            Runbook öffnen →
          </a>
          <a
            href="/check"
            className="px-6 py-3 rounded-2xl border border-white/10 font-bold text-gray-200 hover:border-white/20 transition-all duration-300"
          >
            Security Check
          </a>
        </div>
      </div>
    )
  }

  const prBody = [
    `## 🔧 Automated Fix: ${fixData.title}`,
    "",
    `**Runbook:** https://clawguru.org/runbook/${slug}`,
    `**Fix Generator:** https://clawguru.org/fix/${slug}`,
    "",
    "### Problem",
    fixData.problemDescription,
    "",
    "### Solution",
    fixData.solutionDescription,
    "",
    "### Files Changed",
    fixData.files.map(f => `- \`${f.filename}\``).join("\n"),
    "",
    "### Testing",
    fixData.testingSteps.map(s => `- [ ] ${s}`).join("\n"),
    "",
    "---",
    "_Auto-generated by [ClawGuru WorldBeast](https://clawguru.org) 🦞_",
  ].join("\n")

  function copyPR() {
    navigator.clipboard.writeText(prBody).then(() => {
      setPrCopied(true)
      setTimeout(() => setPrCopied(false), 2000)
    })
  }

  return (
    <div>
      {/* WORLD BEAST UPGRADE: Fix overview */}
      <div className="p-5 rounded-2xl glass-panel mb-6">
        <div className="flex items-center gap-3 mb-3">
          <div
            className="text-xs font-bold px-3 py-1 rounded-full uppercase"
            style={{
              color: fixData.severity === "critical" ? "#ff3b5c" : fixData.severity === "high" ? "#ff6b35" : "#ffcc00",
              background: "rgba(255,255,255,0.05)",
              border: "1px solid rgba(255,255,255,0.1)",
            }}
          >
            {fixData.severity}
          </div>
          <div className="text-xs text-gray-500 font-mono">{fixData.estimatedTime}</div>
        </div>
        <h2 className="text-2xl font-black font-heading mb-2">{fixData.title}</h2>
        <p className="text-gray-400 text-sm">{fixData.problemDescription}</p>
        <p className="text-gray-300 text-sm mt-2">{fixData.solutionDescription}</p>
      </div>

      {/* WORLD BEAST UPGRADE: Tab switcher */}
      <div className="flex gap-2 mb-4">
        <button
          onClick={() => setPrMode(false)}
          className="px-4 py-2 rounded-xl text-sm font-bold transition-all duration-200"
          style={{
            background: !prMode ? "rgba(0, 184, 255, 0.15)" : "rgba(255,255,255,0.04)",
            border: !prMode ? "1px solid rgba(0, 184, 255, 0.3)" : "1px solid rgba(255,255,255,0.08)",
            color: !prMode ? "#00b8ff" : "#888",
          }}
        >
          💻 Code Files
        </button>
        <button
          onClick={() => setPrMode(true)}
          className="px-4 py-2 rounded-xl text-sm font-bold transition-all duration-200"
          style={{
            background: prMode ? "rgba(0, 184, 255, 0.15)" : "rgba(255,255,255,0.04)",
            border: prMode ? "1px solid rgba(0, 184, 255, 0.3)" : "1px solid rgba(255,255,255,0.08)",
            color: prMode ? "#00b8ff" : "#888",
          }}
        >
          🔀 GitHub PR Description
        </button>
      </div>

      {/* WORLD BEAST UPGRADE: Code files view */}
      {!prMode && (
        <div>
          {fixData.files.map((file) => (
            <CodeBlock
              key={file.filename}
              label={file.filename}
              code={file.content}
              lang={file.language}
            />
          ))}
          {/* Testing checklist */}
          {fixData.testingSteps.length > 0 && (
            <div className="p-4 rounded-xl glass-card">
              <div className="font-black text-sm mb-2">✅ Testing Checklist</div>
              <ul className="space-y-1">
                {fixData.testingSteps.map((step, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                    <span className="text-gray-600 mt-0.5">☐</span>
                    <span>{step}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {/* WORLD BEAST UPGRADE: GitHub PR description view */}
      {prMode && (
        <div>
          <div className="rounded-xl overflow-hidden glass-card">
            <div className="flex items-center justify-between px-4 py-2 border-b border-white/5">
              <span className="text-xs text-gray-400 font-mono">PR description · Markdown</span>
              <button
                onClick={copyPR}
                className="text-xs px-3 py-1 rounded-lg transition-all duration-200 font-mono"
                style={{
                  background: prCopied ? "rgba(0, 255, 157, 0.15)" : "rgba(255,255,255,0.06)",
                  color: prCopied ? "#00ff9d" : "#aaa",
                  border: `1px solid ${prCopied ? "rgba(0, 255, 157, 0.3)" : "rgba(255,255,255,0.08)"}`,
                }}
              >
                {prCopied ? "✅ Copied" : "📋 Copy PR"}
              </button>
            </div>
            <pre className="p-4 text-sm text-gray-300 overflow-x-auto font-mono leading-relaxed whitespace-pre-wrap">
              {prBody}
            </pre>
          </div>
          <div className="mt-4 p-4 rounded-xl glass-card text-xs text-gray-500">
            💡 Copy the PR description above, then open a new Pull Request on GitHub and paste it into the description field.
          </div>
        </div>
      )}
    </div>
  )
}
